apiVersion: external-secrets.io/v1
kind: ClusterSecretStore

metadata:
  name: aws-secrets-manager

spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2

      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-sm-credentials
            key: access-key-id
            namespace: external-secrets

          secretAccessKeySecretRef:
            name: aws-sm-credentials
            key: secret-access-key
            namespace: external-secrets
